name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Golang bindings from libnbd v${{ github.ref }}
